### ISSUE TITLE
Uncaught TypeError: Cannot read property 'Constructor' of undefined

### ISSUE THREAD

**Issue by srjahir32** [snapappointments/bootstrap-select-temp#10]
I am using Angular 5 and Boostrap 4. 
Installed boostrap-select v1.13.0-beta. 
loading app shows below error.
![screenshot_10](https://user-images.githubusercontent.com/8255635/36729856-92b0800a-1beb-11e8-95b7-6f81e58cf29e.png)

I made sure that jQuery is being loaded before boostrap-select.js
When I use boostrap-select v1.12,  it does not show this error, but dropdown is not working with this version.

**Comment by fergusbisset** [comment]
I had this issue, but using the non-minified version in the repo instead, seems to work around it...

**Comment by caseyjhol** [comment]
Can you link me to an example? Are you sure you're loading Bootstrap before bootstrap-select?

**Comment by srjahir32** [comment]
@caseyjhol Actually I am using Bootstrap template with angular 5. And temaplate is using ng-Bootstrap.
But even after that, I've added Boostrap CSS, JS and required supported js files before Bootstrap-select. And now it is working perfectly. By the way thanks for making it compatible with bootstrap 4.

**Comment by caseyjhol** [comment]
Happy to hear you got it working!

**Comment by antr1ksh** [comment]
@caseyjhol , I am facing the same issue. Defining bootstrap-select version as $.fn.selectpicker.Constructor.BootstrapVersion = '4';  but it gives the above mentioned error. I am importing bootstrap before select - 
import 'bootstrap';
import 'bootstrap-select';

![image](https://user-images.githubusercontent.com/18299681/97964874-7c953d80-1ddf-11eb-8b2e-bba0018758e9.png)

Bootstrap-select version - 1.13.18
JQuery version - 5.3.1

**Comment by caseyjhol** [comment]
Please take a look in https://github.com/snapappointments/bootstrap-select.
