### ISSUE TITLE
why new repo?

### ISSUE THREAD

**Issue by ko06** [snapappointments/bootstrap-select-temp#12]
may I know the reason for the new repository?

**Comment by sacharbit** [comment]
You're kinda right, it's the main idea of branches but who really cares?

**Comment by silviomoreto** [comment]
Hi @ko06 and @sacharbit  ! Actually, we part ways on the plugin development. We are looking for new maintainers on the old repo if you want to help!

**Comment by caseyjhol** [comment]
After actively developing bootstrap-select for over 5 and a half years and writing close to 30,000 lines of code, I wanted full control of the project to ensure I could take it in the right direction. I also wanted the ability to add collaborators and update the project's description, as well as adjust other repository settings without having to always contact Silvio, thus speeding up development.

Seeing as Silvio hasn't shown much interest in the project the past 5 years, I was hoping he would be willing to transfer ownership to me to simplify things and ease the transition for the community. He has his reasons for not wanting to do that, though, so I opted to fork the original repository and continue my development here.
