### ISSUE TITLE
Purely numeric `data-subtext` breaks live search

### ISSUE THREAD

**Issue by daremon** [snapappointments/bootstrap-select-temp#13]
An option like 
```
<option data-subtext="123">text</option>
```
will break live search with error `Uncaught TypeError: j.toUpperCase is not a function`

I fixed it by changing [this line](https://github.com/snapappointments/bootstrap-select/blob/v1.13.0-dev/js/bootstrap-select.js?utf8=%E2%9C%93#L170) to 
```
string = string.toString().toUpperCase();
```

DEMO: http://jsfiddle.net/mfrup5bL/238/
ENV: bootstrap-select v1.13.0 with BS4

**Comment by caseyjhol** [comment]
Released in [v1.13.0](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.0)!
