### ISSUE TITLE
Select not visible inside modal bootstrap 4

### ISSUE THREAD

**Issue by teoSalvetti** [snapappointments/bootstrap-select-temp#14]
I'm using it with Thymleaf and Bootstrap 4. 
I need to use it inside a modal, but it doens't appear..
Why?

I just tried this:
```
......
<div class="modal-body">
					<select id="lunchBegins" class="selectpicker" data-live-search="true" data-live-search-style="begins" title="Please select a lunch ...">
  <option>Hot Dog, Fries and a Soda</option>
  <option>Burger, Shake and a Smile</option>
  <option>Sugar, Spice and all things nice</option>
  <option>Baby Back Ribs</option>
  <option>A really really long option made to illustrate an issue with the live search in an inline form</option>
</select>

.....
</div>
```

**Comment by caseyjhol** [comment]
It's working in my testing. Are you using v1.13.0-beta? If you're using any version earlier than that, bootstrap-select will not work with Bootstrap 4.

Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/snapappointments/bootstrap-select/blob/master/CONTRIBUTING.md), please create a reduced test case via [Plunker](https://developer.snapappointments.com/bootstrap-select/playground/), [jsFiddle](https://jsfiddle.net/), [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/), and report back with your link, Bootstrap version, bootstrap-select version, and specific browser and OS details.

**Comment by ko06** [comment]
It's working fine on mine ..can you share code  through jsfiddle

**Comment by teoSalvetti** [comment]
Yes, I tried to use the version 12.04.. 
I'll try with the 13.
Thank you
