### ISSUE TITLE
Bower compatibility

### ISSUE THREAD

**Issue by cseelus** [snapappointments/bootstrap-select-temp#16]
Thanks for your work regarding Bootstrap-select.

I know Bower isn't the hottest thing anymore, but some build processes still depend on it.

Would you be willing to accept a PR adding support for Bower, via a bower.json?

```javascript
{
  "name": "bootstrap-select",
  "description": "Bootstrap-select is a jQuery plugin that utilizes Bootstrap's dropdown.js to style and bring additional functionality to standard select elements.",
  "main": [
    "less/bootstrap-select.less",
    "dist/css/bootstrap-select.css",
    "dist/js/bootstrap-select.js"
  ],
  "authors": [
    "Casey Holzer"
  ],
  "license": "MIT",
  "keywords": [
    "form",
    "bootstrap",
    "select",
    "replacement"
  ],
  "homepage": "https://developer.snapappointments.com/bootstrap-select",
  "dependencies": {
    "jquery": ">=1.8"
  },
  "ignore": [
    ".gitignore",
    "CONTRIBUTING.md",
    "Gruntfile.js",
    "README.md",
    "composer.json",
    "package.json",
    "test.html",
    "docs"
  ]
}
```

**Comment by caseyjhol** [comment]
Bower used to be included, but I removed it with v1.13.0-beta, as there are better solutions available now, and Bootstrap dropped support as well. However, I may have jumped the gun. It's not hurting anything to add support for Bower back in, and if people are still using it, there's not really a disadvantage to keeping it. I'll add support back in an upcoming update, and will make it available as either v1.13.0 or v1.13.0-beta.1.

**Comment by cseelus** [comment]
That was fast, thanks!

Would you be ok if this repo gets registered on bower.io? If so, which name would you prefer?

**Comment by caseyjhol** [comment]
@cseelus I've updated the Bower registry to point to this repo (`bower install bootstrap-select` should install from this repo, although the actual bower info won't be updated until the next full release).

**Comment by cseelus** [comment]
Great, thanks again!
