### ISSUE TITLE
Data-thumbnail option

### ISSUE THREAD

**Issue by mobile2ds** [snapappointments/bootstrap-select-temp#18]
I woul like to use image beside text. I found this example **Select with Thumbnails** [here](https://thdoan.github.io/bootstrap-select/examples.html).
But on your latest version 1.12.4 looking the source code this option is not available anymore. How can use images on latest version?

**Comment by PhilPJL** [comment]
@mobile2ds 
You had me worried there for a moment.  However icons work fine.  Test it yourself.

Bootstrap 3.3.7 + Bootstrap select 1.13.0-beta.

![image](https://user-images.githubusercontent.com/271656/37587343-f69a218c-2b56-11e8-9d97-5e7eef6e1d07.png)

**Comment by Fredo70** [comment]
You can use the ettribute data-content:
``` html
<option value="h:464e" data-content="<img class='grayscale email' src='email.png'></img> E-Mail">E-Mail</option>
```
![bootstrap-select-icons](https://user-images.githubusercontent.com/6943043/37610820-ef4f1906-2ba0-11e8-8b6b-45d20a4d9968.png)

**Comment by mobile2ds** [comment]
Thanks.
