### ISSUE TITLE
Support for input-group-prepend

### ISSUE THREAD

**Issue by mrlife** [snapappointments/bootstrap-select-temp#19]
Currently, the input-group-prepend (input group addon) does not render correctly. It both is too small in width and maintains rounded corners on the side with the addon.

jQuery 3.1.1
Bootstrap 4.0.0
bootstrap-select 1.13.0-beta

Here is a live example that shows both a correctly and incorrectly displayed dropdown: https://jsfiddle.net/p3xe2753

**Comment by mrlife** [comment]
Thank you, @caseyjhol. Do you have an anticipated v1.13.0 release date?

**Comment by caseyjhol** [comment]
Released in [v1.13.0](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.0)!
