### ISSUE TITLE
In Bootstrap 4, form control sizing classes don't work

### ISSUE THREAD

**Issue by NoOorZ24** [snapappointments/bootstrap-select-temp#2]
select button doesn't inherit **class="form-control-sm"**

**Comment by caseyjhol** [comment]
Released in [v1.13.0](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.0)!

**Comment by caseyjhol** [comment]
'/move <br><br>:octocat: *Sent from [GH](http://nodegh.io).*
