### ISSUE TITLE
FontAwesome instead of glyphicons

### ISSUE THREAD

**Issue by petrakid** [snapappointments/bootstrap-select-temp#23]
With Bootstrap 4, Glyphicons is no longer included as standard.  As such, some have opted to use FontAwesome instead.

I know that the js automatically adds the "glyphicon" class when data-icon is used.  Is there a cheat which will make it add the "fa" class instead?  The new Fontawesome version also has fas and far classes for variations on the icons.

**Comment by caseyjhol** [comment]
You can set `iconBase` to match whatever font you're using.

https://developer.snapappointments.com/bootstrap-select/options/

```js
$.fn.selectpicker.Constructor.DEFAULTS.iconBase = 'fa';
```

**Comment by petrakid** [comment]
Will this work with the Version 5 of Font Awesome?

**Comment by sreyemnayr** [comment]
@petrakid 
I was able to get it to work with Font Awesome v5 by changing the span.check-mark to svg.check-mark in the css files.

**Comment by petrakid** [comment]
Alright thanks.  Worked for me too.
