### ISSUE TITLE
Cannot set property '_menu' of undefined

### ISSUE THREAD

**Issue by nmanzanos** [snapappointments/bootstrap-select-temp#25]
I hav this error with new beta, using bootstrap 4.

**Cannot set property '_menu' of undefined**

Im using last beta and last popper.js

**Comment by caseyjhol** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/snapappointments/bootstrap-select/blob/master/CONTRIBUTING.md), please create a reduced test case via [Plunker](https://developer.snapappointments.com/bootstrap-select/playground/), [jsFiddle](https://jsfiddle.net/), [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/), and report back with your link, Bootstrap version, bootstrap-select version, and specific browser and OS details.

**Comment by Licenser** [comment]
FWIW running into the same issue

**Comment by Licenser** [comment]
I think it was related to using the bootstra-v4-dev npm instead of the bootstrap npm / hope it helps

**Comment by rodolfosouza** [comment]
I updated to "4.0.0-beta.3" https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-beta.3/js/bootstrap.min.js and its is ok now

**Comment by nmanzanos** [comment]
Solved by @rodolfosouza
