### ISSUE TITLE
Bootstrap 4 validation pseudo classes not being applied properly when new options are appended dynamically

### ISSUE THREAD

**Issue by GiuseppeMobijay** [snapappointments/bootstrap-select-temp#26]
Hi,
Thank you for sharing bootstrap-select with the community.

I'm using the 1.13.0-beta version with bootstrap 4 and its validation.
https://jsfiddle.net/2cLc359h/28/

It works fine, but when new <option> appended on select then it recognizes the select as valid also if any value is selected

**Comment by caseyjhol** [comment]
This seems to be working as expected to me. If an option isn't selected, the select is invalid. If an option is selected, the select is valid. Can you elaborate a bit on the problem?

**Comment by GiuseppeMobijay** [comment]
You're right, I miss some important detail in explaination.
It works fine without add dinamically any option.

But if you click on "add option" link (that append one more option), the validation stop to works correctly, and despite any option selected it mark as valid (green border)

**Comment by caseyjhol** [comment]
Hrmmm - here's the steps I'm following:

1. Click "add option"
2. Click "Submit"
3. See a red border on both the select and the "other control" element

You say you're seeing a green border for step 3? What browser are you using?

**Comment by GiuseppeMobijay** [comment]
Yes, just as you described!

With Chrome works fine.
With firefox 59.0.1 can't work as expected (green border on selectpicker)

**Comment by caseyjhol** [comment]
I see the issue. Even though the value of the placeholder option is empty, Firefox is falling back to the option's text for the value, so it "thinks" a value is actually set for the select. I don't see why the text of the placeholder option even needs to be set, so it should be an easy fix.

**Comment by caseyjhol** [comment]
This actually looks like it's a bug with Firefox. Appending/prepending options is throwing off the validation pseudo classes somehow. I can make a change to make appending work with bootstrap-select, but prepending doesn't work properly even with a standard select (https://jsfiddle.net/2cLc359h/62/).

**Comment by GiuseppeMobijay** [comment]
thank you

**Comment by caseyjhol** [comment]
Released in [v1.13.0](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.0)!
