### ISSUE TITLE
Question: Is there a way to use this component as a "List View"?

### ISSUE THREAD

**Issue by fernandomantoan** [snapappointments/bootstrap-select-temp#28]
First of all I would like to thank you guys for sharing this component with the community, I've used it in quite a few projects until now.

But a requirement of a project that I'm developing is to have a list of items selected/deselected in a similar way of a List View, so the options picker would always be displayed with the "ticker" mark to identify the selected ones, eliminating the `<select>` entirely.

<img width="192" alt="screen shot 2018-03-28 at 19 45 44" src="https://user-images.githubusercontent.com/210359/38060344-aac031d6-32c0-11e8-8970-865ea1750d5a.png">

I did not find any option related to this in the docs and before modifying the component I wondered if you guys would suggest any approach to achieve this requirement. The functionality of the component would be very similar to this one: https://google.github.io/closure-library/source/closure/goog/demos/  if you click "Gmail Bugs" or "Reference" the item will then be selected/deselected.

I found some snippets in Bootsnipp ([like this one](https://bootsnipp.com/snippets/featured/checked-list-group)) but as bootstrap-select is wonderful I would prefer to use it instead of the Bootsnipp approach.

I don't know if this is the proper place to be asking questions but I would appreciate any suggestions.

Regards.

**Comment by caseyjhol** [comment]
There's not currently an easy way to implement this. To improve performance, the menu items aren't actually rendered until the menu is opened. It would be possible to do this with a bit of work, though. I could implement it as an option if there was enough support from the community. If you opt to give this a shot, I'd be happy to help you with any questions.

You could probably start by disabling virtualScroll and triggering setSize on load and go from there.
