### ISSUE TITLE
LiveSearch in bootstrap4

### ISSUE THREAD

**Issue by artlevitan** [snapappointments/bootstrap-select-temp#29]
1. in Safari LiveSearch does not work
2. if there are several selectpiker on the page, then the LiveSearch focus remains on the latter, but it is necessary that the focus should be stylized when expanding select

**Comment by caseyjhol** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/snapappointments/bootstrap-select/blob/master/CONTRIBUTING.md), please create a reduced test case via [Plunker](https://developer.snapappointments.com/bootstrap-select/playground/), [jsFiddle](https://jsfiddle.net/), [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/), and report back with your link, Bootstrap version, bootstrap-select version, and specific browser and OS details.

**Comment by rodolfosouza** [comment]
I have the issue 
`$select.append($('<option />', { 'data-content': '<img src='+img+' class="img-drop"> aaaa', value: 10 }));	`
http://jsfiddle.net/t1m3Lxpg/12/

EDIT: I found the solution, now I need include text:"xxxx" on line 
http://jsfiddle.net/t1m3Lxpg/15/
