### ISSUE TITLE
bug live-search with data-content

### ISSUE THREAD

**Issue by rodolfosouza** [snapappointments/bootstrap-select-temp#31]
I am migrating my old version to new boostrao 4 version and I found a issue.

When I add imagem using data-content the search stops to work

$select.append($('<option />', { 'data-content': '<img src='+img+' class="img-drop"> aaaa', value: 10 }));

http://jsfiddle.net/t1m3Lxpg/12/

**Comment by caseyjhol** [comment]
Released in [v1.13.0](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.0)!
