### ISSUE TITLE
Background color, border and selected row color are different from bootstrap 3

### ISSUE THREAD

**Issue by baumann74** [snapappointments/bootstrap-select-temp#34]
Please see this Plunker: https://plnkr.co/edit/27bFFrsp1wBaUAowclhP 

It is a simple bootstrap-select using bootstrap 4 and bootstrap-select v1.13.0-beta.

The background color of the select element is Athens Gray (#f8f9fa) It has no border, and the selected row color is blue. See images below. 

How do I get the standard style from bootstrap 3 (https://silviomoreto.github.io/bootstrap-select/examples/)? Do I really need to do custom styling to get that?

![bootstrap4-select01](https://user-images.githubusercontent.com/7603096/38468100-17cc0746-3b4a-11e8-9379-fdaf444fbb4d.png)

![bootstrap4-select02](https://user-images.githubusercontent.com/7603096/38468103-1d47fd9c-3b4a-11e8-952c-379979f22f36.png)

**Comment by caseyjhol** [comment]
Bootstrap-select tries to use as much of Bootstrap's styling as possible. So, if you don't like the default styling of Bootstrap 4, you'll have to style it yourself (or find a theme that styles Bootstrap similarly to Bootstrap 3). You can change the button class using `data-style` (I opted to use `btn-light` as the default class, as they removed `btn-default`).
