### ISSUE TITLE
After selection, menu does not close. [GIF included] [CoreUI]

### ISSUE THREAD

**Issue by marchershey** [snapappointments/bootstrap-select-temp#36]
So, it's hard to explain what my select options are doing, so I recorded a GIF. Basically, once I click an option, it is highlighted but never closed. 

IGNORE THE MOUSE POSITION. 

https://i.imgur.com/CJOqbQ0.gif

**Comment by caseyjhol** [comment]
Is it possible you're including Bootstrap JS more than once? Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/snapappointments/bootstrap-select/blob/master/CONTRIBUTING.md), please create a reduced test case via [Plunker](https://developer.snapappointments.com/bootstrap-select/playground/), [jsFiddle](https://jsfiddle.net/), [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/), and report back with your link, Bootstrap version, bootstrap-select version, and specific browser and OS details.

**Comment by marchershey** [comment]
Wow! Thank you for the very fast reply. 

So here was the deal. I am using [CoreUI](https://github.com/coreui) Ajax version. In CoreUI's _app.js_ there is a function to load (a[href]) links into the view, and it just so happens that the select's options are <a> links as well so there was a conflict...

Just for future reference (if you come across this again) here is my fix. 

Inside **app.js** (line ~130ish) 
```
$(document).on('click', 'a[href!="#"]', function(e) {
  var thisNav = $(this).parent().parent();
  if ( thisNav.hasClass('nav-tabs') || thisNav.hasClass('nav-pills') ) {
    e.preventDefault();
  } else if ( $(this).attr('target') == '_top' ) {
    e.preventDefault();
    var target = $(e.currentTarget);
    window.location = (target.attr('href'));
  } else if ( $(this).attr('target') == '_blank' ) {
    e.preventDefault();
    var target = $(e.currentTarget);
    window.open(target.attr('href'));
  } else {
    e.preventDefault();
    var target = $(e.currentTarget);
    setUpUrl(target.attr('href'));
  }
});
```

I added the following "_if_" around the inside of the above function...

```
if ( $(this).attr('role') != 'option' ) {
   ...
}
```

...so it looks like this:

```
  $(document).on('click', 'a[href!="#"]', function(e) {
    if ( $(this).attr('role') != 'option' ) {
      var thisNav = $(this).parent().parent();
      if ( thisNav.hasClass('nav-tabs') || thisNav.hasClass('nav-pills') ) {
        e.preventDefault();
      } else if ( $(this).attr('target') == '_top' ) {
        e.preventDefault();
        var target = $(e.currentTarget);
        window.location = (target.attr('href'));
      } else if ( $(this).attr('target') == '_blank' ) {
        e.preventDefault();
        var target = $(e.currentTarget);
        window.open(target.attr('href'));
      } else {
        e.preventDefault();
        var target = $(e.currentTarget);
        setUpUrl(target.attr('href'));
      }
    }
  });
```

...and now it's working perfectly. I'm currently as I type this editing the stylesheet to match my theme and so far so good. Thanks for this amazing plugin! 

Here's it working 100%: https://i.imgur.com/M6iMhhn.gif

Again, thank you for the very fast response, and amazing plugin!
