### ISSUE TITLE
Bootstrap 4 Live Search -> Active item is "blank"

### ISSUE THREAD

**Issue by ghost** [snapappointments/bootstrap-select-temp#37]
The default CSS for an active item in the dropdown on Bootstrap 4 is "white", so consider to add this line to the css file:

.dropdown-item.active{color:#000;}

thanks.

**Comment by caseyjhol** [comment]
The default background color for an active item is also dark blue...so the text should be readable. Black text would be difficult to read against a dark blue background.

**Comment by ghost** [comment]
Hmm. So, I guess I will just add it to my "custom" css file and that's fine .. Thanks again!
