### ISSUE TITLE
Conflict with Bootstrap bundle (bootstrap.bundle.min.js)

### ISSUE THREAD

**Issue by MilenFrom** [snapappointments/bootstrap-select-temp#4]
When bootsrap bundle is loaded instead of popper.min.js you have to double click on menu to activate and then to be able to actually select an item.

[Fiddle example](https://jsfiddle.net/paw671ka/2/)

**Comment by caseyjhol** [comment]
That's because you're also loading bootstrap.min.js (in addition to bootstrap.bundle.min.js). If you only load bootstrap.bundle.min.js, it works.

**Comment by MilenFrom** [comment]
Ah missed that.
It's working.
Thank you!
