### ISSUE TITLE
HTML content in the subtext get escaped in 1.13.0

### ISSUE THREAD

**Issue by jfcherng** [snapappointments/bootstrap-select-temp#46]
# Environment

- jquery 3.3.1
- bootstrap 3.3.7
- bootstrap-select 1.12.4 / 1.13.0

# JsFiddle

- 1.12.4: https://jsfiddle.net/jfcherng/uux33ge4/
- 1.13.0: https://jsfiddle.net/jfcherng/dho62rmk/

# Screenshot

![image](https://user-images.githubusercontent.com/6594915/39030745-927bd458-4496-11e8-855c-7d5dd7d8060e.png)

**Comment by caseyjhol** [comment]
Fixed and released in [v1.13.1](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.1)!

**Comment by jfcherng** [comment]
@caseyjhol Thanks you. :grinning:
