### ISSUE TITLE
select in navbar (update error)

### ISSUE THREAD

**Issue by felixvictor** [snapappointments/bootstrap-select-temp#5]
bootstrap-select 1.13.0-beta, bootstrap 4

Opening a select in a navbar a second time (open -> close -> open) leads to the error
`Uncaught TypeError: Cannot read property 'update' of null`

Responsible code line 
`if (this.dropdown) this.dropdown._popper.update();`

[Live example](https://jsfiddle.net/felixvictor/34jrnkob/)

Update: From the bootstrap [docs](https://getbootstrap.com/docs/4.0/components/dropdowns/)
> Popper.js isn’t used to position dropdowns in navbars though as dynamic positioning isn’t required.

**Comment by caseyjhol** [comment]
Released in [v1.13.0](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.0)!

**Comment by pepe95270** [comment]
Regression in v1.13.1  ;)

Thanks for your time

**Comment by caseyjhol** [comment]
@pepe95270 I can't recreate this issue with v1.13.1: https://jsfiddle.net/adh7yf19/.
