### ISSUE TITLE
'auto' width not working

### ISSUE THREAD

**Issue by bazineta** [snapappointments/bootstrap-select-temp#53]
While 'auto' width in the past has worked properly, resulting in a selector width equal to that of the widest option, it's not working now. This is visible in the examples in the documentation, where instead of being as wide as it needs to be, the select spans the full width of the container -- it's wider than any of the other width demos below it.

https://developer.snapappointments.com/bootstrap-select/examples/#styling

**Comment by caseyjhol** [comment]
Good catch. I originally chalked this up to an issue with Bootstrap 4, but the problem is occurring with Bootstrap 3 as well.

v1.12.4: https://plnkr.co/edit/Iis43L9hSmUNdAQupYhr?p=preview
v1.13.1: https://plnkr.co/edit/XYd7d6CEyZ1cyiseLNy6?p=preview

**Comment by bazineta** [comment]
In testing on Bootstrap 3 (lining things up to migrate to 4, and we use this great plugin a lot), the change is improved, but still not quite the same as the old version.

In one instance, we've got a select that contains  only the numbers 10, 20, and 50. With the old version, 'auto' minimally sizes; it's really just wide enough to fit the numbers and the caret, which is ideal. With the new version, including this change, it's better, but still substantially wider than the old version is.
