### ISSUE TITLE
When data-container is set, first click resets scroll position

### ISSUE THREAD

**Issue by jmjdev** [snapappointments/bootstrap-select-temp#54]
Hi,

I've noticed that when the data-container attribute is set, when the drop-down is initially selected, the scroll position resets to zero (the top of the page). Though when the drop-down is selected a second time the scroll position is retained.

This is also evident here:
[http://developer.snapappointments.com/bootstrap-select/examples/#container](http://developer.snapappointments.com/bootstrap-select/examples/#container)

Any idea on how this may be fixed?

Thanks,

Jack

**Comment by caseyjhol** [comment]
This issue appears to only occur with Bootstrap 4. I'm guessing it has something to do with Popper.

**Comment by caseyjhol** [comment]
Same as silviomoreto/bootstrap-select#1950.
