### ISSUE TITLE
mobile picker dismisses native picker instantly

### ISSUE THREAD

**Issue by ansonl** [snapappointments/bootstrap-select-temp#55]
When setting `.selectpicker('mobile')`, on iOS 11.3 Safari, the native picker appears for a split second and is then hidden. There is no way to select any options or use the picker on mobile. 

Example html and js code:
```
<select class="selectpicker" id="location-dropdown-btn" data-width="100%" data-style="btn-secondary" data-live-search="true" title="Select a Space-A location" data-toggle="tooltip">
	<option value="">Latest Flights</option>
</select>

<script>
$('#location-dropdown-btn').selectpicker('mobile')
</script>
```

Additionally, is there a way to disable the mobile style as well or have this feature added in? 

I would like to set the mobile style as the safe default and change it to normal style if I detect a capable browser. Thanks.

**Comment by sinneren** [comment]
Confirm issue, bug from 12.4 original plugin, actual for 11+ iOS and mobile touch emulation on Chrome Dev Tools. Without "mobile" option. Clean "open" class name when touch. But in clean demo work fine.
And work when long tap.  Here the demo: https://jsfiddle.net/sinneren/9tae6atb/1/

**Comment by caseyjhol** [comment]
@ansonl Does the problem persist if you set `data-mobile="true"` on the select itself?

**Comment by ansonl** [comment]
@caseyjhol Yes, the problem still persists.

**Comment by caseyjhol** [comment]
What version of Bootstrap and Bootstrap-select are you using?

**Comment by ansonl** [comment]
Bootstrap v4.1.0
Bootstrap-select v1.13.1

**Comment by caseyjhol** [comment]
See silviomoreto/bootstrap-select#1828.
