### ISSUE TITLE
Support custom filtering

### ISSUE THREAD

**Issue by yoeriboven** [snapappointments/bootstrap-select-temp#56]
It might be a good idea to let the user do the filtering. Currently I'm working on a project in which I want the search to be done in the _value_ of the option or in the text with _startsWith_ as the option.

This could be done like this:

```
$('.selectpicker').on('typed.bs.select', function (input) {
  // Filter results here
  	
  return results; // Array of results
});
```

Any suggestions?

**Comment by devjerry** [comment]
I'm in similar need.

In addition to setting `'startsWith'` or `'contains'` in `liveSearchStyle` option, there should be an option to pass custom function for filtering.

Something similar as https://select2.org/searching

### Example:
Let's say I have following selectbox:
```html
<select class="selectpicker" data-live-search="true">
    <option value="1">Paris - Black office</option>
    <option value="2">Paris - Red office</option>
    <option value="3">London - Black office</option>
    <option value="4">London - Red office</option>
</select>
```
After typing `don bla` I would like to have `London - Black office` in search results. So I would write my custom filtering function like this:
```javascript
$('.selectpicker').selectpicker({
    liveSearchStyle: function(searchTerm, item) {
        return searchTerm.toLowerCase().split(' ').every(function(word) {
            return item.toLowerCase().indexOf(word) !== -1;
        });
    }
});
```
In the example `item` parameter represented current text of `<option>`. I would imagine it could be an object containing different parameters of current item in iteration (e.g. it's index, `<option>` text, `<option>` value, if it's inside `<optgroup>`, ...).
