### ISSUE TITLE
Image in custom content stays visible if selected

### ISSUE THREAD

**Issue by Jogai** [snapappointments/bootstrap-select-temp#57]
Tested this on Chrome and Firefox: https://codepen.io/jogai/pen/RyQoda

On selecting an item with an image the selectpicker closes, but the image stays visible.

**Comment by caseyjhol** [comment]
Hrmmm...I can't reproduce this in Chrome or Firefox on Windows. What OS are you using?

**Comment by Jogai** [comment]
Sorry, I applied my workaround already.. Commented the fix in the example, so you can check again.

(I'm on windows 10, but I dont think that matters)

**Comment by Jogai** [comment]
Its with anything, I updated the example with a new testcase.

**Comment by kameshvinayaka** [comment]
Hi, Iam also facing same issue, on select option it show data content data in button with overflow
