### ISSUE TITLE
Using bootstrap-select with Angular 5

### ISSUE THREAD

**Issue by davemvp** [snapappointments/bootstrap-select-temp#58]
bootstrap-select does not work with Angular 5 built with the Angular CLI.

1. Create new application using Angular CLI using ng new

1. Using npm install jquery 1.11.3, bootstrap 3.3.7, and bootstrap-select. Install related @types using --save-dev option

1. Add the bootstrap-select.js file reference in the scripts node in the angular-cli.json file.

1. Add the snippet below to your app.component.ts file
`import * as $ from 'jquery';`
`...`
` ngOnInit(): void {
    $('.select-picker').selectpicker();
   }`

1. This will give you the following error when transpiling using ng build.

> error TS2339: Property 'selectpicker' does not exist on type 'JQuery<HTMLElement>'

This is related to the following issues reported in the original bootstrap-select repository:
[Issue1648](https://github.com/silviomoreto/bootstrap-select/issues/1648)
[Issue1896](https://github.com/silviomoreto/bootstrap-select/issues/1896)

**Comment by majidnk01** [comment]
I have the same issue... problem in using bootstrap-select with Angular

**Installed packages:**
```
...
    "@angular/core": "^6.0.2",
    "@ng-bootstrap/ng-bootstrap": "^2.0.0",
    "bootstrap": "^4.0.0",
    "bootstrap-select": "^1.13.1",
    "jquery": "3.3.1",
```

**added** 
```
         "scripts": [
              "node_modules/jquery/dist/jquery.min.js",
              "node_modules/bootstrap-select/dist/js/bootstrap-select.min.js",
               ...
            ],
```

**and this into style.scss**

`@import "../node_modules/bootstrap-select/dist/css/bootstrap-select.css";
`
Problem:
It works perfectly if I manually hit the URL but does not show the select if I come to URL using ng routing

Any help appreciated!

**Comment by majidnk01** [comment]
Okay it is resolved:

**Solution:**

**Step 0:**

`npm install jquery -- save
`

and in **_typings.d.ts_**

`declare var jQuery: any;
`

**Step 1:**
`npm install bootstrap-select --save
`

**Step 2:**
In **_angular.json_** insert script **after** bootstrap (if exists) and jquery (compulsory)
```
              "node_modules/jquery/dist/jquery.min.js",
               ...
              "node_modules/bootstrap/dist/js/bootstrap.min.js",
               ...
              "node_modules/bootstrap-select/dist/js/bootstrap-select.min.js"
```

**Step 3:**
in **_style.scss_** import css (after bootsrap css if exists)
```
@import "../node_modules/bootstrap/scss/bootstrap";
@import "../node_modules/bootstrap-select/dist/css/bootstrap-select.css";
```

**Step 4:**
In component where its going to be used:

```
  ngAfterViewInit() {
    document.getElementById('preloader').classList.add('hide');
    jQuery('select').selectpicker();
  }  
```

And done, simply use in html like below

```
<select class="form-control selectpicker" data-live-search="true" [formControl]="countryCode">
      <option *ngFor="let country of allCountries" title="{{country[2]}}">
          {{country[0]}} +{{country[2]}}
      </option>
</select>
```

Thanks bootstrap-select team for this awesome job

Regards
