### ISSUE TITLE
Extra 'caret` icon 

### ISSUE THREAD

**Issue by emage** [snapappointments/bootstrap-select-temp#6]
Bootstrap 4 comes with a `caret` icon already append via the :after.  This version adds another caret via the 'bs-caret`.  I use CSS to display: none for now.

**Comment by caseyjhol** [comment]
Can you link me to an example? The code for the other caret (used for Bootstrap 3) is there, but it shouldn't be visible.

**Comment by caseyjhol** [comment]
Released in [v1.13.0](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.0)!
