### ISSUE TITLE
Select / Deselect All buttons are modifying disabled options

### ISSUE THREAD

**Issue by slolo2000** [snapappointments/bootstrap-select-temp#60]
Hello,

Is it normal that the Select All & Deselect All with data-actions-box="true" select or deselect even disabled options?

In source code (changeAll method), I don't see anything that let me believe that it is a supported behavior to let disabled options in their original state.
Cold you add it in the next release please as an option (for example: data-select-disabled="true")

Thanks in advanced for your answer and have a nice day.

**Comment by caseyjhol** [comment]
It's not normal, and appears to be a bug that was introduced in v1.13.0. Working on a fix that should be available in v1.13.2.

**Comment by slolo2000** [comment]
What a fast answer, thank you very much.

Waiting for for the next release, I will use data-hide-disabled="true" to avoid selecting disabled options.
