### ISSUE TITLE
Dropdown doesn't open

### ISSUE THREAD

**Issue by gillesheinesch** [snapappointments/bootstrap-select-temp#61]
The dropdown doesn't open in version 1.13.1 when I click on a selectpicker for example.

1. Include the cdn links of bootstrap select 1.13.1 in the header of your index.html
2. Create a selectpicker
3. Click on on the select dropdown menu
4. Check the console
---> Console: https://i.imgur.com/hmXByxg.png

**Comment by jeffbeagley** [comment]
Can you recreate this within a fiddle?

**Comment by caseyjhol** [comment]
Are you including Bootstrap? Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/snapappointments/bootstrap-select/blob/master/CONTRIBUTING.md), please create a reduced test case via [Plunker](https://developer.snapappointments.com/bootstrap-select/playground/), [jsFiddle](https://jsfiddle.net/), [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/), and report back with your link, Bootstrap version, bootstrap-select version, and specific browser and OS details.

**Comment by gillesheinesch** [comment]
Hello, sorry I forgot about that!
https://jsfiddle.net/f65t9du7/

Bootstrap select version: 1.13.1
Browser: Google Chrome
OS: Windows 10 Build 16299

**Comment by gillesheinesch** [comment]
I think popper.js was missing. 
Works now, thank you!
