### ISSUE TITLE
Dropup doesn't work but dropdown does

### ISSUE THREAD

**Issue by gillesheinesch** [snapappointments/bootstrap-select-temp#62]
Dropup doesn't work but dropdown does. You can see my specific problem in my jsfiddle

I use windows 10, google chrome as browser

1. Create a normal form with the selectpicker class and live search bar
2. Scroll until bootrap-select needs to use dropup
3. You can just see the live search bar but no li entries

https://jsfiddle.net/6j1kz8ee/

**Comment by caseyjhol** [comment]
It's because you're including Bootstrap 3.3.7 CSS in addition to Bootstrap 4 CSS.
