### ISSUE TITLE
bootstrap-select.js:797 Uncaught TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by Dhara-ZYMR** [snapappointments/bootstrap-select-temp#67]
I am using bootstrap-select with its angularjs directive [Ng-bootstrap-select](https://github.com/snapappointments/ng-bootstrap-select)

I am getting following error while scrolling through the options of the select box
```
    bootstrap-select.js:797 Uncaught TypeError: Cannot read property '0' of undefined
        at scroll (bootstrap-select.js:797)
        at HTMLDivElement.<anonymous> (bootstrap-select.js:738)
        at HTMLDivElement.dispatch (jquery.js:5206)
        at HTMLDivElement.elemData.handle (jquery.js:5014)
```

```
angular.js:14794 TypeError: Cannot read property '0' of undefined
    at scroll (bootstrap-select.js:797)
    at Selectpicker.createView (bootstrap-select.js:735)
    at Selectpicker.setSize (bootstrap-select.js:1684)
    at Selectpicker.refresh (bootstrap-select.js:2546)
    at HTMLSelectElement.<anonymous> (bootstrap-select.js:2612)
    at Function.each (jquery.js:362)
    at jQuery.fn.init.each (jquery.js:157)
    at jQuery.fn.init.Plugin [as selectpicker] (bootstrap-select.js:2592)
    at ng-bootstrap-select.js:294
    at Scope.$eval (angular.js:18521)
```

Please note following things:
1. I am using multiple selectboxes on my page. Each select box options are based on the values selected of the previous select-box.
I send a $http request to get the options of the select-box based on the previous box value selected.
2. Another problem is that the dependent options also don't get refreshed when the dynamic options are fetched again for the same select-box

Trying to create a jsfiddle to demonstrate this issue. 
Thanks in advance for help

**Comment by caseyjhol** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/snapappointments/bootstrap-select/blob/master/CONTRIBUTING.md), please create a reduced test case via [Plunker](https://developer.snapappointments.com/bootstrap-select/playground/), [jsFiddle](https://jsfiddle.net/), [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/), and report back with your link, Angular version, Bootstrap version, bootstrap-select version, and specific browser and OS details.

**Comment by Dhara-ZYMR** [comment]
Angular version: 1.6
Bootstrap version 4
bootstrap-select version 1.13.1

As I said I have options coming in dynamically using APIs, and the options are also refreshed based on the previous select-box selection.
I tried to create a test-case but I am not able to reproduce it there.

But in my application, I have this problem everywhere I use bootstrap-select.
Any other way I can show you the issue I am facing? Like Skype or Zoom ?
