### ISSUE TITLE
Dividers broken on bootstrap 4

### ISSUE THREAD

**Issue by wagnerflo** [snapappointments/bootstrap-select-temp#68]
Dividers are generated with `mainElements.push(generateLI(false, index, 'divider'))`. Hardcoding the CSS class is obviously wrong for bootstrap 4 support; use `classNames.DIVIDER` instead.

**Comment by Maximvdw** [comment]
Should add that the proposed fix will cause dividers to break with the "select all" buttons, as the data of the element will be null
