### ISSUE TITLE
Can't choose select option if bootstrap-select is nested within dropdown-menu

### ISSUE THREAD

**Issue by paramono** [snapappointments/bootstrap-select-temp#7]
If I put bootstrap-select input inside a .dropdown-menu, I won't be able to choose anything from it; the options dropdown simply doesn't open on click. I am referring to that particular feature: https://getbootstrap.com/docs/4.0/components/dropdowns/#menu-forms

If I understand correctly, this issue is due to the fact that bootstrap4 doesn't support nested dropdowns (https://github.com/twbs/bootstrap/issues/21026). If so, is there any workaround to make bootstrap-select usable in dropdown-menus?

**Comment by thanatos11** [comment]
Adding this class helped me:

 .dropdown-menu.inner{
            display: block;
 }
