### ISSUE TITLE
data-max-options="1" error

### ISSUE THREAD

**Issue by ghost** [snapappointments/bootstrap-select-temp#77]
Setting data-max-options not working when is 1.

When defined with 1, it's accepting select many options in dropdown list, but in control just last is showed.

I'm using 1.13.1 version of bootstrap-select with Chrome 67.0.3396.99. In Microsoft Edge the error happen too.

Check the print:

![image](https://user-images.githubusercontent.com/16536892/42516407-5cba85ac-8434-11e8-8720-4650c51e3ad6.png)

**Comment by brettwinters** [comment]
same issue here: 

[link](https://jsfiddle.net/Lxrqytf5/2/)
