### ISSUE TITLE
data- attribute not working

### ISSUE THREAD

**Issue by zoigecyb** [snapappointments/bootstrap-select-temp#79]
after many tries i saw that if declaration is
`<label>exampl
<select class="selectpicker">`
`<option>any</option>`
`</select></label>`
any of data- attributes, except data-style not working

**Comment by ghost** [comment]
This issue was moved by [caseyjhol](https://github.com/caseyjhol) to [snapappointments/bootstrap-select#2025](https://github.com/snapappointments/bootstrap-select/issues/2025).
