### ISSUE TITLE
Dropdown options are invisible when using CSS

### ISSUE THREAD

**Issue by mdigi** [snapappointments/bootstrap-select-temp#8]
I'm using the new bootstrap card with a bootstrap-select menu inside the body. When using CSS to change the color of the card's header text, the options in the dropdown disappear unless you hover over the options.
 [Fiddle here](https://jsfiddle.net/rhja1Lcd/6/)

**Comment by mkraha** [comment]
Why you can't use: https://jsfiddle.net/mkrahamath/rhja1Lcd/8/
```
.card-header a {
  color: #FFF;
} 
```

**Comment by mdigi** [comment]
OK that works. What I have makes all of the text in the card white (including the dropdown). Thanks.

**Comment by mkraha** [comment]
Use this: https://jsfiddle.net/mkrahamath/rhja1Lcd/14/
```
.card a {
  color: #FFF;
}
.bootstrap-select a {
  color:#000;
}
```
