### ISSUE TITLE
Arrow down key doesn't scroll the view to the top when data-size is set

### ISSUE THREAD

**Issue by abraaosantos** [snapappointments/bootstrap-select-temp#82]
Hi,

I've noticed that, when using the data-size attribute, if you navigate through the options using the arrow keys the view doesn't scroll to top when the last option is reached and you press the arrow down key.

The menu size example has this problem: https://developer.snapappointments.com/bootstrap-select/examples/#menu-size

**Comment by ghost** [comment]
This issue was moved by [caseyjhol](https://github.com/caseyjhol) to [snapappointments/bootstrap-select#2024](https://github.com/snapappointments/bootstrap-select/issues/2024).
