### ISSUE TITLE
Long Option text not adding horizontal scrollbar

### ISSUE THREAD

**Issue by Dhara-ZYMR** [snapappointments/bootstrap-select-temp#87]
When there is long text in option, the container is not adding a horizontal scrollbar. I have used data-container="body".
Please check the fiddle for it: https://jsfiddle.net/DharaZymr/2cLc359h/90/

**Comment by Dhara-ZYMR** [comment]
Currently adding a hack to fix it using CSS. Giving fix width like below
`.bs-container.dropdown.bootstrap-select {
    .dropdown-menu.show {
        width: 400px !important;
        min-width: 400px !important;
    }
}`

This is not the perfect solution, please do let me know if there is a proper solution for this.

**Comment by ghost** [comment]
This issue was moved by [caseyjhol](https://github.com/caseyjhol) to [snapappointments/bootstrap-select#2020](https://github.com/snapappointments/bootstrap-select/issues/2020).
