### ISSUE TITLE
Document how to add select options programmatically

### ISSUE THREAD

**Issue by alexlenail** [snapappointments/bootstrap-select-temp#88]
Is there an API to add options programmatically, or are we expected to do this with jquery and then [refresh](https://developer.snapappointments.com/bootstrap-select/methods/#selectpickerrefresh)? Either way, would love to see mention of this use case in the docs.

**Comment by ghost** [comment]
This issue was moved by [caseyjhol](https://github.com/caseyjhol) to [snapappointments/bootstrap-select#2019](https://github.com/snapappointments/bootstrap-select/issues/2019).
