### ISSUE TITLE
Dropdown-menu can't place properly

### ISSUE THREAD

**Issue by Arunkarthik07** [snapappointments/bootstrap-select-temp#89]
Hi,
When I scroll the container, drop-down struct with the top bar.it doesn't properly follow the parent element.

please check the codepen for it: https://codepen.io/Arunkarthik07/pen/bjOLYV

![screen shot 2018-08-10 at 1 42 26 pm](https://user-images.githubusercontent.com/42264605/43946628-620c3708-9ca3-11e8-9f25-1ab1c4def231.png)

**Comment by ghost** [comment]
This issue was moved by [caseyjhol](https://github.com/caseyjhol) to [snapappointments/bootstrap-select#2018](https://github.com/snapappointments/bootstrap-select/issues/2018).
