### ISSUE TITLE
.empty() method is not working

### ISSUE THREAD

**Issue by mdigi** [snapappointments/bootstrap-select-temp#9]
I'm trying to empty the contents of a select dropdown menu and it seems like it only works when the first item is selected. 

[Here's the example](https://plnkr.co/edit/jatRiz2IKhYceFeIk2uz)

When the second or third value is selected in the dropdown and the button is pressed to empty the contents, it clears out the selection. However if you click on the dropdown again, all of the values are still there.

If the 1st value of the dropdown is selected and the button pressed, then it seems to work fine.

**Comment by fergusbisset** [comment]
I had this issue, but using the non-minified version in the repo instead solved this...

**Comment by caseyjhol** [comment]
Released in [v1.13.0](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.0)!
