### ISSUE TITLE
How to get all selected elements?

### ISSUE THREAD

**Issue by Seriousness** [snapappointments/bootstrap-select-temp#90]
I couldnt get an array with all selected elements and didnt find anything in the documentation am I stupid or how to get the selected elements in an js array? Jquery is possible.

**Comment by Seriousness** [comment]
found it:

var targets = [];
$.each($(".selectpicker option:selected"), function(){
targets.push($(this).val());
});
alert("You have selected the targets - " + targets.join(", "))

**Comment by jeffbeagley** [comment]
When you enable to select multiple elements, they're all automatically added to an array accessible via 

`$( "#element" ).val(); //returns array [1,2,3]`
